# Generated by Django 4.2.6 on 2023-11-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_autor_museo_tecnica_photo_date_photo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
